# Site settings
title: Zwei’s Blog
SEOTitle: Zwei's Blog
header-img: img/pdao.webp
email: post@zwei.de.eu.org
description: "这里是 @Zwei 的个人博客，与你一起发现更大的世界 | 我要学知识！"
keyword: "CS, Deutsch, AI, 德语, 信息安全, 全栈, Zwei, @Zwei, Zwei的博客, Zwei's Blog, 博客, 个人网站, 互联网 ,计算机, 信息安全, Web, JavaScript, 前端, 大学生"
url: "https://zwei.de.eu.org" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username: null
# zhihu_username: null
github_username: bestZwei
# twitter_username: null
#facebook_username:  null
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: ZWEI

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: zwei.de.eu.org
# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "萌新程序员 <br> 准大三打工人 <br> post@zwei.de.eu.org"
sidebar-avatar: https://s21.ax1x.com/2024/07/02/pkguIN4.md.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#F7EED6"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "Charliez0", href: "https://github.com/charliez0" },
  ]
